FROM almalinux:9
LABEL COURSE="DevOps" \
      TRAINER="pavan" \
      DURATION="120HRS" \
      com.joindevops.dockerfile.author="pavan@mail.com"

#docker images --filter "lable=course=DevOps" this command was used for filetring images